### PR TITLE
Added first draft of services Form

### PR DESCRIPTION
**Pull request by cleferman**
- updated checkbox control to pass ref and className
- updated radio control to pass ref and className
- added className prop to `ElementWrapper`
- added className and labelPosition to `Input`
- added several translation strings for services Form
- added form for `transport marfă`

## not sure where to put custom styling, shoved them in globals.css

# Partial commit to serve as an example, can't close the services form issue yet.

### What does it fix?

Closes #XXX

### CODE REVIEW

**Comment by cleferman** [comment]
Preview: image
Error messages are easily customizable didn't get around to that. 
Need to properly style controls inside radio buttons
Submit button is there just for easy testing until we get everything.

Couldn't do much today so I opened this PR if anyone wants to continue, as I'll only be available again in the evening.

**Comment by virgilbugnariu** [comment]
I'll make an issue regarding the error messages and I'll fix it separately.

**Comment by virgilbugnariu** [comment]
Actually, now that I've looked over the changeset:
1. Maybe we should add two new components, RadioGroup and CheckboxGroup that will show only one error message? Feels weird to show the same error message under each radio/checkbox element.
2. I believe same styling regarding horizontal positioned labels can be achieved using tailwind.

I can make these changes.

**Comment by virgilbugnariu** [comment]
Made this PR to merge into this branch.

https://github.com/code4romania/war-support-sprijin-de-urgenta-client/pull/64

**Pull request closed without merging**
